export type Kursart = "VKU" | "Nothelferkurs" | "VKU + Nothelfer";

export interface Anbieter {
  id: string;
  name: string;
  ort: string;
  plz: string;
  quartier: string;
  kanton: string;
  kursarten: Kursart[];
  dauer: string;
  preis: number;
  rating: number;
  bewertungen: number;
  naechsterTermin: string;
}

export const KANTONE = [
  "Zürich",
  "Bern",
  "Basel-Stadt",
  "Luzern",
  "St. Gallen",
  "Aargau",
  "Winterthur",
] as const;

export const ANBIETER: Anbieter[] = [
  {
    id: "fahren-verstand-zh",
    name: "Fahren & Verstand Zürich-Ost",
    ort: "Zürich",
    plz: "8032",
    quartier: "Wollishofen",
    kanton: "Zürich",
    kursarten: ["VKU"],
    dauer: "4 × 2 Lektionen",
    preis: 95,
    rating: 4.8,
    bewertungen: 63,
    naechsterTermin: "Di, 2. Sept, 18:30",
  },
  {
    id: "erste-hilfe-akademie",
    name: "Erste Hilfe Akademie",
    ort: "Zürich",
    plz: "8006",
    quartier: "Rigiblick",
    kanton: "Zürich",
    kursarten: ["Nothelferkurs"],
    dauer: "10 Stunden",
    preis: 120,
    rating: 4.9,
    bewertungen: 41,
    naechsterTermin: "Sa, 6. Sept, 09:00",
  },
  {
    id: "fuehrerschein-paket-nord",
    name: "Führerschein-Paket Zürich-Nord",
    ort: "Zürich",
    plz: "8050",
    quartier: "Oerlikon",
    kanton: "Zürich",
    kursarten: ["VKU", "Nothelferkurs"],
    dauer: "Kombi-Paket",
    preis: 180,
    rating: 4.7,
    bewertungen: 88,
    naechsterTermin: "Mo, 1. Sept, 17:00",
  },
  {
    id: "vku-zentrum-winterthur",
    name: "VKU Zentrum Winterthur",
    ort: "Winterthur",
    plz: "8400",
    quartier: "Altstadt",
    kanton: "Zürich",
    kursarten: ["VKU"],
    dauer: "4 × 2 Lektionen",
    preis: 89,
    rating: 4.6,
    bewertungen: 124,
    naechsterTermin: "Do, 4. Sept, 18:00",
  },
  {
    id: "srk-bern-nothelfer",
    name: "Nothelferkurs Bern West",
    ort: "Bern",
    plz: "3007",
    quartier: "Länggasse",
    kanton: "Bern",
    kursarten: ["Nothelferkurs"],
    dauer: "10 Stunden",
    preis: 110,
    rating: 4.8,
    bewertungen: 97,
    naechsterTermin: "Fr, 5. Sept, 13:00",
  },
  {
    id: "fahrschule-linden-be",
    name: "Fahrschule Linden",
    ort: "Bern",
    plz: "3011",
    quartier: "Innere Stadt",
    kanton: "Bern",
    kursarten: ["VKU", "Nothelferkurs"],
    dauer: "Kombi-Paket",
    preis: 165,
    rating: 4.9,
    bewertungen: 203,
    naechsterTermin: "Mi, 3. Sept, 18:30",
  },
  {
    id: "vku-basel-stadt",
    name: "Verkehrskunde Basel",
    ort: "Basel",
    plz: "4051",
    quartier: "Grossbasel",
    kanton: "Basel-Stadt",
    kursarten: ["VKU"],
    dauer: "4 × 2 Lektionen",
    preis: 98,
    rating: 4.5,
    bewertungen: 56,
    naechsterTermin: "Di, 9. Sept, 18:00",
  },
  {
    id: "nothelfer-luzern",
    name: "Erste Hilfe Luzern",
    ort: "Luzern",
    plz: "6003",
    quartier: "Altstadt",
    kanton: "Luzern",
    kursarten: ["Nothelferkurs"],
    dauer: "10 Stunden",
    preis: 115,
    rating: 4.7,
    bewertungen: 72,
    naechsterTermin: "Sa, 13. Sept, 08:30",
  },
  {
    id: "vku-stgallen",
    name: "VKU Punkt St. Gallen",
    ort: "St. Gallen",
    plz: "9000",
    quartier: "Bahnhof",
    kanton: "St. Gallen",
    kursarten: ["VKU"],
    dauer: "4 × 2 Lektionen",
    preis: 92,
    rating: 4.6,
    bewertungen: 45,
    naechsterTermin: "Mo, 8. Sept, 19:00",
  },
  {
    id: "premiers-secours-geneve",
    name: "Premiers Secours Genève",
    ort: "Genf",
    plz: "1204",
    quartier: "Plainpalais",
    kanton: "Genf",
    kursarten: ["Nothelferkurs"],
    dauer: "10 Stunden",
    preis: 130,
    rating: 4.7,
    bewertungen: 64,
    naechsterTermin: "Sa, 6. Sept, 10:00",
  },
  {
    id: "vku-lausanne",
    name: "Sensibilisation Lausanne",
    ort: "Lausanne",
    plz: "1003",
    quartier: "Centre",
    kanton: "Waadt",
    kursarten: ["VKU"],
    dauer: "4 × 2 Lektionen",
    preis: 105,
    rating: 4.4,
    bewertungen: 38,
    naechsterTermin: "Do, 11. Sept, 18:15",
  },
  {
    id: "fahrschule-aarau",
    name: "Fahrschule Aarau Mitte",
    ort: "Aarau",
    plz: "5000",
    quartier: "Bahnhofplatz",
    kanton: "Aargau",
    kursarten: ["VKU", "Nothelferkurs"],
    dauer: "Kombi-Paket",
    preis: 155,
    rating: 4.8,
    bewertungen: 51,
    naechsterTermin: "Mi, 10. Sept, 18:00",
  },
  {
    id: "pronto-soccorso-lugano",
    name: "Primo Soccorso Lugano",
    ort: "Lugano",
    plz: "6900",
    quartier: "Centro",
    kanton: "Tessin",
    kursarten: ["Nothelferkurs"],
    dauer: "10 Stunden",
    preis: 125,
    rating: 4.6,
    bewertungen: 29,
    naechsterTermin: "Sa, 20. Sept, 09:30",
  },
  {
    id: "vku-zuerich-west",
    name: "VKU Zürich West",
    ort: "Zürich",
    plz: "8005",
    quartier: "Hardbrücke",
    kanton: "Zürich",
    kursarten: ["VKU"],
    dauer: "4 × 2 Lektionen",
    preis: 99,
    rating: 4.7,
    bewertungen: 112,
    naechsterTermin: "Fr, 5. Sept, 18:45",
  },
  {
    id: "nothelfer-zuerich-see",
    name: "Nothelfer Plus Zürichsee",
    ort: "Zürich",
    plz: "8008",
    quartier: "Seefeld",
    kanton: "Zürich",
    kursarten: ["Nothelferkurs"],
    dauer: "10 Stunden",
    preis: 118,
    rating: 4.8,
    bewertungen: 76,
    naechsterTermin: "So, 7. Sept, 09:00",
  },
];
