/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as DatenschutzRouteImport } from './routes/datenschutz'
import { Route as FahrschulenPartnerRouteImport } from './routes/fahrschulen-partner'
import { Route as ImpressumRouteImport } from './routes/impressum'
import { Route as KombiPlanerRouteImport } from './routes/kombi-planer'
import { Route as KombiangeboteRouteImport } from './routes/kombiangebote'
import { Route as KontaktRouteImport } from './routes/kontakt'
import { Route as RatgeberRouteImport } from './routes/ratgeber'
import { Route as UeberUnsRouteImport } from './routes/ueber-uns'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedMeinKontoRouteImport } from './routes/_authenticated/mein-konto'
import { Route as AnbieterSlugRouteImport } from './routes/anbieter.$slug'
import { Route as NothelferkursIndexRouteImport } from './routes/nothelferkurs.index'
import { Route as NothelferkursKantonRouteImport } from './routes/nothelferkurs.$kanton'
import { Route as VkuIndexRouteImport } from './routes/vku.index'
import { Route as VkuKantonRouteImport } from './routes/vku.$kanton'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const DatenschutzRoute = DatenschutzRouteImport.update({
  id: '/datenschutz',
  path: '/datenschutz',
  getParentRoute: () => rootRouteImport,
} as any)
const FahrschulenPartnerRoute = FahrschulenPartnerRouteImport.update({
  id: '/fahrschulen-partner',
  path: '/fahrschulen-partner',
  getParentRoute: () => rootRouteImport,
} as any)
const ImpressumRoute = ImpressumRouteImport.update({
  id: '/impressum',
  path: '/impressum',
  getParentRoute: () => rootRouteImport,
} as any)
const KombiPlanerRoute = KombiPlanerRouteImport.update({
  id: '/kombi-planer',
  path: '/kombi-planer',
  getParentRoute: () => rootRouteImport,
} as any)
const KombiangeboteRoute = KombiangeboteRouteImport.update({
  id: '/kombiangebote',
  path: '/kombiangebote',
  getParentRoute: () => rootRouteImport,
} as any)
const KontaktRoute = KontaktRouteImport.update({
  id: '/kontakt',
  path: '/kontakt',
  getParentRoute: () => rootRouteImport,
} as any)
const RatgeberRoute = RatgeberRouteImport.update({
  id: '/ratgeber',
  path: '/ratgeber',
  getParentRoute: () => rootRouteImport,
} as any)
const UeberUnsRoute = UeberUnsRouteImport.update({
  id: '/ueber-uns',
  path: '/ueber-uns',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMeinKontoRoute = AuthenticatedMeinKontoRouteImport.update({
  id: '/mein-konto',
  path: '/mein-konto',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AnbieterSlugRoute = AnbieterSlugRouteImport.update({
  id: '/anbieter/$slug',
  path: '/anbieter/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const NothelferkursIndexRoute = NothelferkursIndexRouteImport.update({
  id: '/nothelferkurs/',
  path: '/nothelferkurs/',
  getParentRoute: () => rootRouteImport,
} as any)
const NothelferkursKantonRoute = NothelferkursKantonRouteImport.update({
  id: '/nothelferkurs/$kanton',
  path: '/nothelferkurs/$kanton',
  getParentRoute: () => rootRouteImport,
} as any)
const VkuIndexRoute = VkuIndexRouteImport.update({
  id: '/vku/',
  path: '/vku/',
  getParentRoute: () => rootRouteImport,
} as any)
const VkuKantonRoute = VkuKantonRouteImport.update({
  id: '/vku/$kanton',
  path: '/vku/$kanton',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/datenschutz': typeof DatenschutzRoute
  '/fahrschulen-partner': typeof FahrschulenPartnerRoute
  '/impressum': typeof ImpressumRoute
  '/kombi-planer': typeof KombiPlanerRoute
  '/kombiangebote': typeof KombiangeboteRoute
  '/kontakt': typeof KontaktRoute
  '/ratgeber': typeof RatgeberRoute
  '/ueber-uns': typeof UeberUnsRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/mein-konto': typeof AuthenticatedMeinKontoRoute
  '/anbieter/$slug': typeof AnbieterSlugRoute
  '/nothelferkurs/$kanton': typeof NothelferkursKantonRoute
  '/vku/$kanton': typeof VkuKantonRoute
  '/nothelferkurs/': typeof NothelferkursIndexRoute
  '/vku/': typeof VkuIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/datenschutz': typeof DatenschutzRoute
  '/fahrschulen-partner': typeof FahrschulenPartnerRoute
  '/impressum': typeof ImpressumRoute
  '/kombi-planer': typeof KombiPlanerRoute
  '/kombiangebote': typeof KombiangeboteRoute
  '/kontakt': typeof KontaktRoute
  '/ratgeber': typeof RatgeberRoute
  '/ueber-uns': typeof UeberUnsRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/mein-konto': typeof AuthenticatedMeinKontoRoute
  '/anbieter/$slug': typeof AnbieterSlugRoute
  '/nothelferkurs/$kanton': typeof NothelferkursKantonRoute
  '/vku/$kanton': typeof VkuKantonRoute
  '/nothelferkurs': typeof NothelferkursIndexRoute
  '/vku': typeof VkuIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/datenschutz': typeof DatenschutzRoute
  '/fahrschulen-partner': typeof FahrschulenPartnerRoute
  '/impressum': typeof ImpressumRoute
  '/kombi-planer': typeof KombiPlanerRoute
  '/kombiangebote': typeof KombiangeboteRoute
  '/kontakt': typeof KontaktRoute
  '/ratgeber': typeof RatgeberRoute
  '/ueber-uns': typeof UeberUnsRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/mein-konto': typeof AuthenticatedMeinKontoRoute
  '/anbieter/$slug': typeof AnbieterSlugRoute
  '/nothelferkurs/$kanton': typeof NothelferkursKantonRoute
  '/vku/$kanton': typeof VkuKantonRoute
  '/nothelferkurs/': typeof NothelferkursIndexRoute
  '/vku/': typeof VkuIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/datenschutz'
    | '/fahrschulen-partner'
    | '/impressum'
    | '/kombi-planer'
    | '/kombiangebote'
    | '/kontakt'
    | '/ratgeber'
    | '/ueber-uns'
    | '/admin'
    | '/mein-konto'
    | '/anbieter/$slug'
    | '/nothelferkurs/$kanton'
    | '/vku/$kanton'
    | '/nothelferkurs/'
    | '/vku/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/datenschutz'
    | '/fahrschulen-partner'
    | '/impressum'
    | '/kombi-planer'
    | '/kombiangebote'
    | '/kontakt'
    | '/ratgeber'
    | '/ueber-uns'
    | '/admin'
    | '/mein-konto'
    | '/anbieter/$slug'
    | '/nothelferkurs/$kanton'
    | '/vku/$kanton'
    | '/nothelferkurs'
    | '/vku'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/datenschutz'
    | '/fahrschulen-partner'
    | '/impressum'
    | '/kombi-planer'
    | '/kombiangebote'
    | '/kontakt'
    | '/ratgeber'
    | '/ueber-uns'
    | '/_authenticated/admin'
    | '/_authenticated/mein-konto'
    | '/anbieter/$slug'
    | '/nothelferkurs/$kanton'
    | '/vku/$kanton'
    | '/nothelferkurs/'
    | '/vku/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  DatenschutzRoute: typeof DatenschutzRoute
  FahrschulenPartnerRoute: typeof FahrschulenPartnerRoute
  ImpressumRoute: typeof ImpressumRoute
  KombiPlanerRoute: typeof KombiPlanerRoute
  KombiangeboteRoute: typeof KombiangeboteRoute
  KontaktRoute: typeof KontaktRoute
  RatgeberRoute: typeof RatgeberRoute
  UeberUnsRoute: typeof UeberUnsRoute
  AnbieterSlugRoute: typeof AnbieterSlugRoute
  NothelferkursKantonRoute: typeof NothelferkursKantonRoute
  VkuKantonRoute: typeof VkuKantonRoute
  NothelferkursIndexRoute: typeof NothelferkursIndexRoute
  VkuIndexRoute: typeof VkuIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/datenschutz': {
      id: '/datenschutz'
      path: '/datenschutz'
      fullPath: '/datenschutz'
      preLoaderRoute: typeof DatenschutzRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fahrschulen-partner': {
      id: '/fahrschulen-partner'
      path: '/fahrschulen-partner'
      fullPath: '/fahrschulen-partner'
      preLoaderRoute: typeof FahrschulenPartnerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/impressum': {
      id: '/impressum'
      path: '/impressum'
      fullPath: '/impressum'
      preLoaderRoute: typeof ImpressumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kombi-planer': {
      id: '/kombi-planer'
      path: '/kombi-planer'
      fullPath: '/kombi-planer'
      preLoaderRoute: typeof KombiPlanerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kombiangebote': {
      id: '/kombiangebote'
      path: '/kombiangebote'
      fullPath: '/kombiangebote'
      preLoaderRoute: typeof KombiangeboteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kontakt': {
      id: '/kontakt'
      path: '/kontakt'
      fullPath: '/kontakt'
      preLoaderRoute: typeof KontaktRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ratgeber': {
      id: '/ratgeber'
      path: '/ratgeber'
      fullPath: '/ratgeber'
      preLoaderRoute: typeof RatgeberRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ueber-uns': {
      id: '/ueber-uns'
      path: '/ueber-uns'
      fullPath: '/ueber-uns'
      preLoaderRoute: typeof UeberUnsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/mein-konto': {
      id: '/_authenticated/mein-konto'
      path: '/mein-konto'
      fullPath: '/mein-konto'
      preLoaderRoute: typeof AuthenticatedMeinKontoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/anbieter/$slug': {
      id: '/anbieter/$slug'
      path: '/anbieter/$slug'
      fullPath: '/anbieter/$slug'
      preLoaderRoute: typeof AnbieterSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nothelferkurs/': {
      id: '/nothelferkurs/'
      path: '/nothelferkurs'
      fullPath: '/nothelferkurs/'
      preLoaderRoute: typeof NothelferkursIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nothelferkurs/$kanton': {
      id: '/nothelferkurs/$kanton'
      path: '/nothelferkurs/$kanton'
      fullPath: '/nothelferkurs/$kanton'
      preLoaderRoute: typeof NothelferkursKantonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vku/': {
      id: '/vku/'
      path: '/vku'
      fullPath: '/vku/'
      preLoaderRoute: typeof VkuIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vku/$kanton': {
      id: '/vku/$kanton'
      path: '/vku/$kanton'
      fullPath: '/vku/$kanton'
      preLoaderRoute: typeof VkuKantonRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedMeinKontoRoute: typeof AuthenticatedMeinKontoRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedMeinKontoRoute: AuthenticatedMeinKontoRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  DatenschutzRoute: DatenschutzRoute,
  FahrschulenPartnerRoute: FahrschulenPartnerRoute,
  ImpressumRoute: ImpressumRoute,
  KombiPlanerRoute: KombiPlanerRoute,
  KombiangeboteRoute: KombiangeboteRoute,
  KontaktRoute: KontaktRoute,
  RatgeberRoute: RatgeberRoute,
  UeberUnsRoute: UeberUnsRoute,
  AnbieterSlugRoute: AnbieterSlugRoute,
  NothelferkursKantonRoute: NothelferkursKantonRoute,
  VkuKantonRoute: VkuKantonRoute,
  NothelferkursIndexRoute: NothelferkursIndexRoute,
  VkuIndexRoute: VkuIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
